---
title: data550_final
author: Drashti Maisuria
output: github_document
---

# Brief description of the contents of the report
This data set is a comprehensive record of the Summer Olympic Games from 1896
to 2024. It shows information about athletes, their performances, and the medals that
were awarded. There is a table where the variable “name of athlete” is removed 
so there is only the player id identifying them. There is also a figure that 
shows the trend of how many males and females medaled throughout the years of 
2000-2024. This can provide insight on the number of male and female winners 
for coming years. This report also shows which country had the most athletes 
received a gold medal.

# How to generate the final report
Requirements
R: Required for running the analysis scripts.
Make: For automating the report generation.
R Packages: Ensure the required R packages are installed

# Code Structure
'00_table.Rmd'
This code will manipulate the data and remove Event. And then it will generate a 
table showing the total number of male and female athletes.The table should be 
saved in the output folder as a csv.

'01_figure.Rmd'
This code will generate a figure that shows the trend of how many males and 
females metaled throughout the years of 2000-2024. The figure should be saved in 
the output folder as a PNG. 

'02_analysis.Rmd'
This code will tell you what country had the most gold medals. 

'final.Rmd' 
This will generate the report. 

-------------------------------------------------------------------------------

The Makefile, Rmarkdown (`final.Rmd`), and HTML report will be in the root 
directory of the project. The Rmarkdown will contain the tables and figures 
produced in the analysis.

data550_final uses `renv` to manage package environment. Run the following command:

Install the required R packages:
   If you have `make` installed, simply run:
   ```bash
   make install
   
   












